export const VANCOUVER_HOODS = {
  kitsilano: {
    slug: "kitsilano", name: "Kitsilano",
    hoodMult: 1.22, vsAvgPct: 22,
    description: "Kitsilano is one of Vancouver's most desirable neighbourhoods, known for its beaches, outdoor lifestyle, and mix of heritage homes and newer rental buildings.",
    context: "Units within walking distance of Kits Beach command the highest premiums.",
    nearbyHoods: ["Point Grey", "Fairview", "West End"],
  },
  yaletown: {
    slug: "yaletown", name: "Yaletown",
    hoodMult: 1.25, vsAvgPct: 25,
    description: "Yaletown is a upscale neighbourhood of converted warehouses and luxury condos in downtown Vancouver, popular with young professionals.",
    context: "Premium finishes and central location push rents consistently above the city average.",
    nearbyHoods: ["Downtown", "West End", "Mount Pleasant"],
  },
  mountpleasant: {
    slug: "mountpleasant", name: "Mount Pleasant",
    hoodMult: 1.04, vsAvgPct: 4,
    description: "Mount Pleasant is a vibrant, arts-focused neighbourhood on the east side of Vancouver with a mix of heritage buildings, breweries, and newer rental developments.",
    context: "Rents are close to the city average, offering good value for a central location.",
    nearbyHoods: ["Main Street", "Fairview", "Commercial Drive"],
  },
  commercialdrive: {
    slug: "commercialdrive", name: "Commercial Drive",
    hoodMult: 0.97, vsAvgPct: -3,
    description: "Commercial Drive is a diverse, community-oriented neighbourhood in East Vancouver known for its independent cafes, restaurants, and strong local character.",
    context: "Rents are slightly below the city average, offering relative value on the east side.",
    nearbyHoods: ["Mount Pleasant", "Grandview Woodland", "Hastings Sunrise"],
  },
  westend: {
    slug: "westend", name: "West End",
    hoodMult: 1.18, vsAvgPct: 18,
    description: "The West End is a dense, walkable neighbourhood adjacent to Stanley Park and English Bay, offering some of Vancouver's most central rental options.",
    context: "Proximity to the beach and downtown drives strong year-round rental demand.",
    nearbyHoods: ["Downtown", "Yaletown", "Kitsilano"],
  },
  fairview: {
    slug: "fairview", name: "Fairview",
    hoodMult: 1.10, vsAvgPct: 10,
    description: "Fairview is a central neighbourhood on the south slope of False Creek, popular with healthcare workers due to its proximity to Vancouver General Hospital.",
    context: "Good transit access and central location support rents above the city average.",
    nearbyHoods: ["Kitsilano", "Mount Pleasant", "Cambie"],
  },
  downtown: {
    slug: "downtown", name: "Downtown Vancouver",
    hoodMult: 1.20, vsAvgPct: 20,
    description: "Downtown Vancouver offers maximum walkability and transit access, with a dense mix of condo rentals and purpose-built buildings close to employment centres.",
    context: "Rents are well above the city average, reflecting the central location and high demand.",
    nearbyHoods: ["West End", "Yaletown", "Gastown"],
  },
  richmond: {
    slug: "richmond", name: "Richmond",
    hoodMult: 0.92, vsAvgPct: -8,
    description: "Richmond is a city south of Vancouver proper, well connected by the Canada Line SkyTrain. It offers more affordable rents than most Vancouver neighbourhoods.",
    context: "Canada Line access keeps demand strong despite the suburban location.",
    nearbyHoods: ["Marpole", "Burnaby", "South Granville"],
  },
  burnaby: {
    slug: "burnaby", name: "Burnaby",
    hoodMult: 0.93, vsAvgPct: -7,
    description: "Burnaby offers a mix of urban and suburban living with strong SkyTrain connections on both the Millennium and Expo lines.",
    context: "Metrotown and Brentwood areas command premiums within Burnaby itself.",
    nearbyHoods: ["Richmond", "New Westminster", "East Vancouver"],
  },
  mainstreet: {
    slug: "main-street", name: "Main Street",
    hoodMult: 1.02, vsAvgPct: 2,
    description: "Main Street is a popular corridor in South Vancouver known for its independent shops, restaurants, and strong sense of community stretching from Mount Pleasant to Marine Drive.",
    context: "Rents are close to the city average, with newer buildings pushing toward the higher end.",
    nearbyHoods: ["Mount Pleasant", "Riley Park", "Fraser"],
  },
  gastown: {
    slug: "gastown", name: "Gastown",
    hoodMult: 1.15, vsAvgPct: 15,
    description: "Gastown is Vancouver's oldest neighbourhood, a National Historic Site known for its cobblestone streets, heritage brick buildings, and growing mix of upscale condos and rental conversions.",
    context: "Above-average rents reflect the heritage character and strong demand from downtown workers.",
    nearbyHoods: ["Downtown Vancouver", "Chinatown", "Strathcona"],
  },
  chinatown: {
    slug: "chinatown", name: "Chinatown",
    hoodMult: 1.00, vsAvgPct: 0,
    description: "Vancouver's Chinatown is a designated National Historic Site and one of the oldest in North America, currently undergoing significant residential development with a mix of heritage and modern rental buildings.",
    context: "Rents are broadly in line with the city average, with newer purpose-built buildings at the higher end.",
    nearbyHoods: ["Gastown", "Strathcona", "Downtown Vancouver"],
  },
  strathcona: {
    slug: "strathcona", name: "Strathcona",
    hoodMult: 0.93, vsAvgPct: -7,
    description: "Strathcona is Vancouver's oldest residential neighbourhood, known for its heritage homes, artist studios, and proximity to the downtown east side. It has seen significant gentrification pressure.",
    context: "Rents are below the city average, but rising due to redevelopment and proximity to downtown.",
    nearbyHoods: ["Chinatown", "Gastown", "Commercial Drive"],
  },
  grandviewwoodland: {
    slug: "grandview-woodland", name: "Grandview-Woodland",
    hoodMult: 0.95, vsAvgPct: -5,
    description: "Grandview-Woodland is a diverse east-side neighbourhood centred on Commercial Drive, known for its strong community identity, mix of housing types, and excellent SkyTrain access.",
    context: "Rents are slightly below the city average, offering value for renters who want proximity to Commercial Drive.",
    nearbyHoods: ["Commercial Drive", "Mount Pleasant", "Hastings-Sunrise"],
  },
  coalharbour: {
    slug: "coal-harbour", name: "Coal Harbour",
    hoodMult: 1.30, vsAvgPct: 30,
    description: "Coal Harbour is an upscale waterfront neighbourhood adjacent to Stanley Park and the downtown core, featuring premium high-rise condos with mountain and water views.",
    context: "Waterfront views and luxury finishes make Coal Harbour one of Vancouver's most expensive rental markets.",
    nearbyHoods: ["West End", "Downtown Vancouver", "Yaletown"],
  },
  southgranville: {
    slug: "south-granville", name: "South Granville",
    hoodMult: 1.12, vsAvgPct: 12,
    description: "South Granville is an upscale west-side corridor known for its art galleries, design shops, and high-end restaurants along Granville Street between Broadway and 16th Avenue.",
    context: "West-side location and proximity to Shaughnessy command above-average rents.",
    nearbyHoods: ["Fairview", "Kerrisdale", "Marpole"],
  },
  kerrisdale: {
    slug: "kerrisdale", name: "Kerrisdale",
    hoodMult: 1.08, vsAvgPct: 8,
    description: "Kerrisdale is a quiet, affluent west-side neighbourhood with excellent schools, a charming village commercial strip, and strong demand from families and professionals.",
    context: "West-side location and good schools keep demand above the city average.",
    nearbyHoods: ["South Granville", "Dunbar", "Marpole"],
  },
  dunbar: {
    slug: "dunbar", name: "Dunbar",
    hoodMult: 1.05, vsAvgPct: 5,
    description: "Dunbar is a low-key, family-friendly west-side neighbourhood near UBC, with quiet residential streets, mature trees, and a mix of houses and low-rise rental buildings.",
    context: "Proximity to UBC and Pacific Spirit Park supports rents modestly above the city average.",
    nearbyHoods: ["Point Grey", "Kerrisdale", "Kitsilano"],
  },
  northvancouver: {
    slug: "north-vancouver", name: "North Vancouver",
    hoodMult: 0.96, vsAvgPct: -4,
    description: "North Vancouver offers mountain access, newer rental stock, and excellent outdoor recreation while maintaining strong transit links to downtown via the SeaBus.",
    context: "Rents are slightly below the Vancouver average, offering value with a mountain lifestyle.",
    nearbyHoods: ["West Vancouver", "Burnaby", "Downtown Vancouver"],
  },
  newwestminster: {
    slug: "new-westminster", name: "New Westminster",
    hoodMult: 0.85, vsAvgPct: -15,
    description: "New Westminster is Metro Vancouver's oldest city, with a revitalized waterfront, frequent SkyTrain access on the Expo and Millennium lines, and some of the region's most affordable rents.",
    context: "Rents are well below the Vancouver average, making New West one of the best value options in the metro area.",
    nearbyHoods: ["Burnaby", "Richmond", "Coquitlam"],
  },
};

export const VANCOUVER_CITY = {
  key: "vancouver", name: "Vancouver", province: "British Columbia",
  accent: "#1a5c34", accentLight: "#f0f7f2", accentBorder: "#a8d5b5",
  calcUrl: "https://vancouverfairrent.ca",
  bases: { bachelor:1950, "1br":2600, "2br":3400, "3br":4300, "3plus":5200 },
  inflation: 0.040, rentControlled: false,
};
